### ISSUE TITLE
compiler-explorer-infra @ 5758145 failed to build on Ubuntu 24.04 due Python 3.12 being default

### ISSUE THREAD

**Issue by sanyaade-teachings** [tylerh111/compiler-explorer-docker#2]
Hi Everyone,

Just a head up that [compiler-explorer-infra @ 5758145 fails to build on Ubuntu 24.04 where Python 3.12 is the default version.
This needs to be upgraded to the main branch tree that supports ubuntu 24.04

God blesses!!!

Regards

**Comment by tylerh111** [comment]
Yeah, I haven't updated this repo in a long while. I'll put some effort in getting this working again with upstream main branches.

**Comment by sanyaade-teachings** [comment]
> Yeah, I haven't updated this repo in a long while. I'll put some effort in getting this working again with upstream main branches.

I am working locally with the main branch of the infra and complier-explorer. 
I was able to build the docker images but I am getting bad requests (502) and also at times, connection refused. 
I will initiate a pull request when everything is running.
Also looking at the possibility of using the docker-compose method

God blesses!!!

Regards

**Comment by tylerh111** [comment]
Man, these scripts are old... Not sure how anything was running before, lol.

I have something working. I was able to run the ce with just gcc 14.2.0 and fmt 11.0.0 (though that didn't show up in the libraries list). It turns out that python need updated to 3.12 (thanks to upgrading to ubuntu 24.04) but also needed to upgrade node to 18. So I included both of those changes. I also updated the submodules to the latest main / tag.

I'll put a PR up soon. If the changes didn't work completely, feel free to create another PR.
